# Generated by Django 3.2 on 2021-04-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, verbose_name='customer')),
                ('item', models.CharField(max_length=100, verbose_name='item')),
                ('total', models.FloatField(verbose_name='total')),
                ('quantity', models.FloatField(verbose_name='quantity')),
                ('date', models.DateTimeField(db_index=True, verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Rich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('spent_money', models.FloatField(blank=True, null=True, verbose_name='Потратил денег за весь период')),
                ('gems', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
    ]
