# Generated by Django 3.2 on 2021-04-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gems_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rich',
        ),
    ]
